// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoef;

#nullable disable

namespace Net.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20220614030821_DatosIniciales")]
    partial class DatosIniciales
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("proyectoef.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("69d20de1-4182-4ce6-98d5-a73d2a50511a"),
                            Descripcion = "Son actividades que necesitan ser terminadas",
                            Nombre = "Actividades en Espera",
                            Peso = 30
                        },
                        new
                        {
                            CategoriaId = new Guid("69d20de1-4182-4ce6-98d5-a73d2a505120"),
                            Descripcion = "Son actividades que estan terminadas",
                            Nombre = "Actividades terminadas",
                            Peso = 20
                        });
                });

            modelBuilder.Entity("proyectoef.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("69d20de1-4182-4ce6-98d5-a73d2a505110"),
                            CategoriaId = new Guid("69d20de1-4182-4ce6-98d5-a73d2a50511a"),
                            Descripcion = "Terminar toda la escuela de C# en platzi hasta fin de mes",
                            FechaCreacion = new DateTime(2022, 6, 13, 22, 8, 21, 471, DateTimeKind.Local).AddTicks(6276),
                            PrioridadTarea = 2,
                            Titulo = "Terminar curso de platzi en c#"
                        },
                        new
                        {
                            TareaId = new Guid("69d20de1-4182-4ce6-98d5-a73d2a505130"),
                            CategoriaId = new Guid("69d20de1-4182-4ce6-98d5-a73d2a505120"),
                            Descripcion = "Ingresar los certificados obtenidos en platzi al CV",
                            FechaCreacion = new DateTime(2022, 6, 13, 22, 8, 21, 471, DateTimeKind.Local).AddTicks(6294),
                            PrioridadTarea = 1,
                            Titulo = "Terminar CV de programador"
                        });
                });

            modelBuilder.Entity("proyectoef.Models.Tarea", b =>
                {
                    b.HasOne("proyectoef.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyectoef.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
